"""initial schema: stores, products, stock, orders, order_items

Revision ID: 0001
Revises:
Create Date: 2026-10-09

Written by hand (not autogenerated) so every line is deliberate.
"alembic check" confirms it matches the models exactly.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _timestamp(name: str) -> sa.Column:
    return sa.Column(
        name, sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
    )


def upgrade() -> None:
    # Order matters: a table must exist before another table references it.
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("code", sa.String(20), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("city", sa.String(60), nullable=False),
        _timestamp("created_at"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("code", name=op.f("uq_stores_code")),
    )

    op.create_table(
        "products",
        sa.Column("sku", sa.String(20), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("category", sa.String(30), nullable=False),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("sku", name=op.f("pk_products")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price_nonneg")),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"])

    op.create_table(
        "stock",
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(20), nullable=False),
        sa.Column("on_hand", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reorder_point", sa.Integer(), server_default="0", nullable=False),
        sa.Column("aisle", sa.String(5), nullable=False),
        sa.Column("bay", sa.String(5), nullable=False),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("store_id", "sku", name=op.f("pk_stock")),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_stock_store_id_stores")
        ),
        sa.ForeignKeyConstraint(
            ["sku"], ["products.sku"], name=op.f("fk_stock_sku_products")
        ),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_stock_on_hand_nonneg")),
        sa.CheckConstraint("reserved >= 0", name=op.f("ck_stock_reserved_nonneg")),
        sa.CheckConstraint(
            "reserved <= on_hand", name=op.f("ck_stock_reserved_le_on_hand")
        ),
        sa.CheckConstraint(
            "reorder_point >= 0", name=op.f("ck_stock_reorder_point_nonneg")
        ),
    )

    op.create_table(
        "orders",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(12), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_orders_store_id_stores")
        ),
        sa.CheckConstraint(
            "status IN ('RESERVED', 'CONFIRMED', 'CANCELLED')",
            name=op.f("ck_orders_status_valid"),
        ),
    )
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"])

    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(20), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(10, 2), nullable=False),
        sa.PrimaryKeyConstraint("order_id", "sku", name=op.f("pk_order_items")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sku"], ["products.sku"], name=op.f("fk_order_items_sku_products")
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_order_items_qty_positive")),
    )


def downgrade() -> None:
    # Reverse order: drop tables that reference others first.
    op.drop_table("order_items")
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("stock")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_table("stores")
